language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  allow_failures:
    - php: 7.1

before_script:
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install -f apcu; composer require atoum/atoum; fi
  - composer self-update
  - composer install

script:
  - bin/phpunit --coverage-text --debug

notifications:
  email:
    on_success: always
    on_failure: always
